### ISSUE TITLE
Hierarchical processes with custom manager with no agent assignment on task causes an error 

### ISSUE THREAD

**Issue by andrewn3** [Scale3-Labs/langtrace#366]
When you define a Hierarchical processes you don't need to specify on the task if it's assigned to an agent as you can let the manager or custom manager do this.    I created a custom manager agent and assigned it to  "manager=" as part of the crew definition and the left the task with no assigned agents as the manager would choose and the langtrace python sdk will fail.

This flagged this error 

File "D:\Users\xxxx\crewai\xxxx\xxx\xxx\.venv\Lib\site-packages\**langtrace_python_sdk\instrumentation\crewai\patch.py", line 226, in _parse_tasks**
    "agent": task.agent.role,**
             ^^^^^^^^^^^^^^^
**AttributeError: 'NoneType' object has no attribute 'role'**

i did a crude fix just to get it working e.g. "agent": task.agent.role if task.agent else None

**Comment by karthikscale3** [comment]
Hi @andrewn3 , thanks for reporting. We will have a fix for it shortly.

**Comment by alizenhom** [comment]
@andrewn3 Nice catch, this now fixed and released in [3.3.12](https://github.com/Scale3-Labs/langtrace-python-sdk/releases/tag/3.3.12) kindly update to 3.3.12 and will be more than happy if you still face any issues

**Comment by andrewn3** [comment]
Works fine with 3.3.12.
